/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import Clases.C_Numero_Perf_Deficiente_Abund;

/**
 *
 * @author USUARIO
 */
public class C_Num_Def_Perf_Abund extends javax.swing.JFrame {

    /**
     * Creates new form Potencia_De_Un_Numero
     */
    public C_Num_Def_Perf_Abund() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 20)); // NOI18N
        jLabel1.setText("Número Deficiente Perfecto o Abundante");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel2.setText("Digita el número: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        numero.setBackground(new java.awt.Color(255, 255, 255));
        numero.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(45, 28, 0), new java.awt.Color(94, 49, 6)));
        getContentPane().add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 79, 28));

        button.setBackground(new java.awt.Color(228, 220, 208));
        button.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        button.setForeground(new java.awt.Color(38, 30, 18));
        button.setText("Calcular");
        button.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(45, 28, 0), null));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        getContentPane().add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 90, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo3.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed

        int num = Integer.parseInt(numero.getText());

        if (C_Numero_Perf_Deficiente_Abund.Calcularsiesabundante(num) == true
                & C_Numero_Perf_Deficiente_Abund.Calcularsiesdeficiente(num) == false
                & C_Numero_Perf_Deficiente_Abund.Calcularsiesperfecto(num) == false) {
            JOptionPane.showMessageDialog(null, "El número ingresado es un número abundante mas no es "
                    + "\n\t\tun número deficiente ni perfecto");
        } else if (C_Numero_Perf_Deficiente_Abund.Calcularsiesabundante(num) == false
                & C_Numero_Perf_Deficiente_Abund.Calcularsiesdeficiente(num) == true
                & C_Numero_Perf_Deficiente_Abund.Calcularsiesperfecto(num) == false) {
            JOptionPane.showMessageDialog(null, "El número ingresado es un número deficiente mas no es "
                    + "\n\t\tun número abundante ni perfecto");
        } else if (C_Numero_Perf_Deficiente_Abund.Calcularsiesabundante(num) == false
                & C_Numero_Perf_Deficiente_Abund.Calcularsiesdeficiente(num) == false
                & C_Numero_Perf_Deficiente_Abund.Calcularsiesperfecto(num) == true) {
            JOptionPane.showMessageDialog(null, "El número ingresado es un número perfecto mas no es "
                    + "\n\t\tun número abundante ni deficiente");
        }

    }//GEN-LAST:event_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_Num_Def_Perf_Abund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_Num_Def_Perf_Abund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_Num_Def_Perf_Abund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_Num_Def_Perf_Abund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new C_Num_Def_Perf_Abund().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField numero;
    // End of variables declaration//GEN-END:variables
}
