/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.M_Ejerc13;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class FPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Taller
     */
    public FPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textfield0 = new javax.swing.JLabel();
        textfield1 = new javax.swing.JLabel();
        textfield2 = new javax.swing.JLabel();
        textfieldOpc = new javax.swing.JTextField();
        buttonA = new javax.swing.JButton();
        buttonC = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textfield3 = new javax.swing.JLabel();
        textfield4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textfield5 = new javax.swing.JLabel();
        textfield6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textfield7 = new javax.swing.JLabel();
        textfield8 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textfield9 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textfield10 = new javax.swing.JLabel();
        textfield11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        jLabel13.setText("10. Decir si un número es capicúa o No");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(0, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(215, 210, 210));
        jLabel1.setText("Elije que quieres hacer:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        textfield0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textfield0.setForeground(new java.awt.Color(197, 188, 188));
        textfield0.setText("0. Salir ");
        getContentPane().add(textfield0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        textfield1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textfield1.setForeground(new java.awt.Color(197, 188, 188));
        textfield1.setText("1. Dados dos (2) números ·”x” y “z”, calcular “x”elevado a la ”z”");
        getContentPane().add(textfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 16));

        textfield2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textfield2.setForeground(new java.awt.Color(197, 188, 188));
        textfield2.setText("2. Dado un (1) número ” x ”, calcular “ x ! ” (x factorial). ");
        getContentPane().add(textfield2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        textfieldOpc.setBackground(new java.awt.Color(230, 210, 213));
        textfieldOpc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textfieldOpc.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 0), new java.awt.Color(209, 185, 133)));
        textfieldOpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldOpcActionPerformed(evt);
            }
        });
        getContentPane().add(textfieldOpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 361, 20));

        buttonA.setBackground(new java.awt.Color(153, 139, 121));
        buttonA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonA.setForeground(new java.awt.Color(51, 51, 0));
        buttonA.setText("Aceptar");
        buttonA.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 0), null));
        buttonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAActionPerformed(evt);
            }
        });
        getContentPane().add(buttonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 650, 80, 30));

        buttonC.setBackground(new java.awt.Color(153, 139, 121));
        buttonC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonC.setForeground(new java.awt.Color(51, 51, 0));
        buttonC.setText("Cancelar");
        buttonC.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 0), null));
        getContentPane().add(buttonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 650, 80, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(197, 188, 188));
        jLabel5.setText("3. Dado un número, calcular si ese número es deficiente, perfecto o abundante.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        textfield3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textfield3.setForeground(new java.awt.Color(197, 188, 188));
        textfield3.setText("4. Dado un número N (de cualquier cantidad de cifras), descomponerlo en sus dígitos y calcular: La sumatoria de sus cifras pares y La sumatoria de las cifras impares. ");
        getContentPane().add(textfield3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 16));

        textfield4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textfield4.setForeground(new java.awt.Color(197, 188, 188));
        textfield4.setText("5. Imprimir los 4 primeros cubos interesantes entre todos los enteros mayores a 1.");
        getContentPane().add(textfield4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(197, 188, 188));
        jLabel6.setText("6. Dado un número entero N por teclado, calcular la siguiente expresión  (X/Y)^Z  donde X es la suma de los divisores pares de N; Y es la suma de los divisores ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        textfield5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textfield5.setForeground(new java.awt.Color(197, 188, 188));
        textfield5.setText("impares de N y Z es el número de dígitos de N.");
        getContentPane().add(textfield5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 16));

        textfield6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textfield6.setForeground(new java.awt.Color(197, 188, 188));
        textfield6.setText("7. Dados dos números X y N enteros positivos,  calcular la siguiente formula matemática:  ((N+(1+X) !)^x)/((X*2)^N!)");
        getContentPane().add(textfield6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(197, 188, 188));
        jLabel7.setText("8. Dados dos número (N,M), decir si son números amigos o no");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        textfield7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textfield7.setForeground(new java.awt.Color(197, 188, 188));
        textfield7.setText("9. Dado un número entero positivo N, acumular y calcular los números perfectos que existen hasta el número N.");
        getContentPane().add(textfield7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 16));

        textfield8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textfield8.setForeground(new java.awt.Color(197, 188, 188));
        textfield8.setText("10. Calcular los números narcisistas que hay del 1 al 10000");
        getContentPane().add(textfield8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(197, 188, 188));
        jLabel8.setText("11. Dado un número N, descomponerlo en tres números de dos dígitos cada uno y calcular la siguiente formula:  ((X! + Z)^Y) / (X+Z)!  donde x, y, z ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        textfield9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textfield9.setForeground(new java.awt.Color(197, 188, 188));
        textfield9.setText("se encuentran en el número N;   Ej:  N = 230411  al descomponer el número  quedaría así:  x=23    y=04   z=11\t ");
        getContentPane().add(textfield9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(197, 188, 188));
        jLabel9.setText("12. Programa que lea el código del estudiante y las notas de los tres cortes (excepto la del examen final), el número de estudiantes es indeterminado; el programa debe determinar la nota");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        textfield10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textfield10.setForeground(new java.awt.Color(197, 188, 188));
        textfield10.setText("acumulada del estudiante, la nota que debe sacar el estudiante para pasar y el porcentaje de estudiantes que tiene el ponderado por encima de 2.5");
        getContentPane().add(textfield10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, 16));

        textfield11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textfield11.setForeground(new java.awt.Color(197, 188, 188));
        textfield11.setText("(Ej:585,25352) y el si la cantidad de cifras es par, averiguar si el número es múltiplo de 4 y termina en 8 (Ej:28).");
        getContentPane().add(textfield11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(197, 188, 188));
        jLabel10.setText("13. Dado un número entero positivo de cualquier cantidad de dígitos (cifras), averigüar e imprimir lo siguiente: si la cantidad de cifras es impar averiguar si el número es capicúa,");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(197, 188, 188));
        jLabel11.setText("14. Programa que registre de N estudiantes, la fecha de nacimiento: día, mes, año; el sexo (1. Hombre o 2 Mujer). Pedir por teclado y una sola vez... la fecha actual Día, Mes y Año;");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(197, 188, 188));
        jLabel12.setText("una vez ingresada esta información, el programa debe: mostrar la edad cumplida de la persona (en años), determinar la vacuna que se debe aplicar el estudiante mostrando el código  ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(197, 188, 188));
        jLabel14.setText("15. Programa que lea el tipo de servicio y el código del libro y si es un código debe determinar si se puede prestar el libro o el valor a cobrar por los libros prestados,");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(197, 188, 188));
        jLabel15.setText("(según el tipo de servicio solicitado) y al final imprimir el total recaudado por prestamos de libros.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(197, 188, 188));
        jLabel16.setText("16. Dado un número de 6 cifras, descomponerlo en tres números, de dos dígitos cada uno, ej: N = 121589\t al descomponer el número a=12  b=15  c=89;  luego realizar lo siguiente: ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(197, 188, 188));
        jLabel17.setText("verificar que sea de 6 dígitos, Si no lo es debe terminar el programa; generar las tablas de multiplicar de a hasta b, donde a debe ser menor que b; formar un numero uniendo a y c;");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(197, 188, 188));
        jLabel18.setText("por último, invertir el número N.");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        jLabel4.setFont(new java.awt.Font("Chiller", 0, 51)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("Ejercicios Matemáticos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 370, -1));

        jLabel19.setForeground(new java.awt.Color(51, 51, 0));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/fondooo.jpg"))); // NOI18N
        jLabel19.setText("jLabel19");
        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 0), null, null));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAActionPerformed

        int Opc = Integer.parseInt(textfieldOpc.getText());

        if (Opc == 0) {
            System.exit(0);
        }
        if (Opc == 1) {
            new A_Potencia_De_Un_Numero().setVisible(true);
        }
        if (Opc == 2) {
            new B_Factorialdeunnum().setVisible(true);
        }
        if (Opc == 3) {
            new C_Num_Def_Perf_Abund().setVisible(true);
        }
        if (Opc == 4) {
            new D_Suma_Cifras_Pares_Impares().setVisible(true);
        }
        if (Opc == 5) {
            JOptionPane.showMessageDialog(null, "Los primeros 4 números cubos interesantes son: "
                    + Clases.E_Primeros4_Cubos_Interesantes.calcular4primeroscubosinteresantes());
        }
        if (Opc == 6) {
            new F_Ejercicio6().setVisible(true);
        }
        if (Opc == 7) {
            new G_Ejercicio7().setVisible(true);
        }
        if (Opc == 8) {
            new H_Números_Amigos().setVisible(true);
        }
        if (Opc == 9) {
            new I_Acumulo_de_NumPerfecto().setVisible(true);
        }
        if (Opc == 10) {
            new J_Numeros_Narcisistas_1_1000().setVisible(true);
        }
        if (Opc == 11) {
            new K_Ejercicio11().setVisible(true);
        }
        if (Opc == 12) {
            new L_Ejercicio12().setVisible(true);
        }
        if (Opc == 13) {
            int num = Integer.parseInt(JOptionPane.showInputDialog("Digite el número, para realizar este ejercicio: "));

            int cantcifras = String.valueOf(num).length();

            if (M_Ejerc13.espar(cantcifras)) {

                if (M_Ejerc13.esmultiplode4(num) == true && M_Ejerc13.terminaen8(num) == true) {
                    JOptionPane.showMessageDialog(null, "El número es multiplo de 4 y termina en 8");
                } else if (M_Ejerc13.esmultiplode4(num) == true && M_Ejerc13.terminaen8(num) == false) {
                    JOptionPane.showMessageDialog(null, "El número es multiplo de 4 y no termina en 8");
                } else if (M_Ejerc13.esmultiplode4(num) == false && M_Ejerc13.terminaen8(num) == true) {
                    JOptionPane.showMessageDialog(null, "El número termina en 8 y no es multiplo de 4");
                } else {
                    JOptionPane.showMessageDialog(null, "El número no es multiplo de 4 y no termina en 8");
                }
            } else {
                if (M_Ejerc13.escapicua(num)) {
                    JOptionPane.showMessageDialog(null, "el número ingresado es un número capicúa");
                } else {
                    JOptionPane.showMessageDialog(null, "el número ingresado no es un número capicúa");
                }
            }

        }
        if (Opc == 14) {
            new N_Programa_Vacunacion().setVisible(true);
        }
        if (Opc == 15) {
            new O_Programa_Biblioteca().setVisible(true);
        }
        if (Opc == 16) {
            new P_TablasMultiplicar_Unir_A_C_Invertirnum().setVisible(true);
        }
    }//GEN-LAST:event_buttonAActionPerformed

    private void textfieldOpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldOpcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldOpcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonA;
    private javax.swing.JButton buttonC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel textfield0;
    private javax.swing.JLabel textfield1;
    private javax.swing.JLabel textfield10;
    private javax.swing.JLabel textfield11;
    private javax.swing.JLabel textfield2;
    private javax.swing.JLabel textfield3;
    private javax.swing.JLabel textfield4;
    private javax.swing.JLabel textfield5;
    private javax.swing.JLabel textfield6;
    private javax.swing.JLabel textfield7;
    private javax.swing.JLabel textfield8;
    private javax.swing.JLabel textfield9;
    private javax.swing.JTextField textfieldOpc;
    // End of variables declaration//GEN-END:variables
}
