
package GUI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Clases.N_Programa_Vac;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Arrays;


public class N_Programa_Vacunacion extends javax.swing.JFrame {

    DefaultTableModel modelo;

    public N_Programa_Vacunacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        String cabecera[] = {"  Cedula  ", "  Sexo  ", " Edad ", " Código ", " Vacuna "};
        String Datos[][] = {};
        modelo = new DefaultTableModel(Datos, cabecera);

        table.setModel(modelo);
        calculate.setEnabled(false);
        //calculate.setOpaque(true);
        calculate.setForeground(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendarCombo1 = new org.freixas.jcalendar.JCalendarCombo();
        fechadenacimiento3 = new org.freixas.jcalendar.JCalendarCombo();
        jScrollPane4 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        fechaactual3 = new org.freixas.jcalendar.JCalendarCombo();
        genero = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fechadenacimiento3.addDateListener(new org.freixas.jcalendar.DateListener() {
            public void dateChanged(org.freixas.jcalendar.DateEvent evt) {
                fechadenacimiento3DateChanged(evt);
            }
        });
        fechadenacimiento3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechadenacimiento3MouseClicked(evt);
            }
        });
        fechadenacimiento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechadenacimiento3ActionPerformed(evt);
            }
        });
        getContentPane().add(fechadenacimiento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 475, 90));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(38, 30, 18));
        jLabel25.setText("Sexo:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        jLabel21.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 23)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(38, 30, 18));
        jLabel21.setText("Vacunación - Universitarios");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 32, -1, -1));

        fechaactual3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaactual3fechaactualActionPerformed(evt);
            }
        });
        getContentPane().add(fechaactual3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoActionPerformed(evt);
            }
        });
        getContentPane().add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(38, 30, 18));
        jLabel24.setText("Fecha de nacimiento:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(38, 30, 18));
        jLabel23.setText("Fecha actual:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel22.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(38, 30, 18));
        jLabel22.setText("Vacunados");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        calculate.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        calculate.setForeground(new java.awt.Color(23, 11, 0));
        calculate.setText("Seleccionar tipo de vacuna");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        getContentPane().add(calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, -1, -1));

        Eliminar.setForeground(new java.awt.Color(19, 5, 0));
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondovaccination2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*ActionListener activebotoncalculate = new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            fechadenacimiento3ActionPerformed(e);
            //calculate.setEnabled(true);
        }
    };*/

    private void fechaactual3fechaactualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaactual3fechaactualActionPerformed

    }//GEN-LAST:event_fechaactual3fechaactualActionPerformed

    private void fechadenacimiento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechadenacimiento3ActionPerformed

        //JOptionPane.showMessageDialog(null, "Entro al private void fechadenacimiento3ActionPerformed");
        /*if (!calculate.isEnabled()) {
            JOptionPane.showMessageDialog(null, "el boton calcular esta deshabilitado, pero yá se habilitó!");
            calculate.setEnabled(true);
        }*/
        //fechadenacimiento3.addActionListener(activebotoncalculate);
        //calculate.setEnabled(true);
    }//GEN-LAST:event_fechadenacimiento3ActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed

        int cedula = Integer.parseInt(JOptionPane.showInputDialog("Cedula del estudiante: "));
        boolean serepite = false;
        for (int i = 0; i < table.getRowCount(); i++) {
            if (cedula == Integer.parseInt((String) table.getValueAt(i, 0))) {
                serepite = true;
            }
        }

        if (serepite) {
            JOptionPane.showMessageDialog(null, "ALERTA!!!"
                    + "\n\nPaciente ya vacunado, NO PUEDE SER VACUNADO NUEVAMENTE!!!");
        } else {
            String gener = genero.getSelectedItem().toString();

            //JOptionPane.showMessageDialog(null, "Fecha actual: " + fechaactual3.getSelectedItem());
            int añoactual = fechaactual3.getCalendar().getWeekYear();
            int añonaci = fechadenacimiento3.getCalendar().getWeekYear();

            /*DateTimeFormatter date = DateTimeFormatter.ofPattern("dd/dd/mm/yyyy");
        LocalDate fechanacimiento = LocalDate.parse((CharSequence) fechadenacimiento3.getSelectedItem(), date);
        LocalDate fechactual = LocalDate.parse((CharSequence) fechaactual3.getSelectedItem(), date);*/
            int edad = N_Programa_Vac.calculoedad(añonaci, añoactual);

            //JOptionPane.showMessageDialog(null, "Edad: " + edad + " años.");
            int codigo = N_Programa_Vac.vacunar(edad, genero.getSelectedIndex());
            String vacuna = "";

            if (codigo == 01) {
                vacuna = "Paperas";
            } else if (codigo == 02) {
                vacuna = "Sarampión";
            }
            if (codigo == 03) {
                vacuna = "Influenza";
            }
            if (codigo == 04) {
                vacuna = "Hepatitis";
            } else if (codigo == 05) {
                vacuna = "Fiebre Amarilla";
            }

            String Datos[] = {String.valueOf(cedula), gener, String.valueOf(edad), String.valueOf(codigo), vacuna};
            modelo.addRow(Datos);
            calculate.setEnabled(false);
        }
        calculate.setEnabled(false);
        //calculate.setOpaque(true);
    }//GEN-LAST:event_calculateActionPerformed

    private void generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoActionPerformed

    }//GEN-LAST:event_generoActionPerformed

    private void fechadenacimiento3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechadenacimiento3MouseClicked

    }//GEN-LAST:event_fechadenacimiento3MouseClicked

    private void fechadenacimiento3DateChanged(org.freixas.jcalendar.DateEvent evt) {//GEN-FIRST:event_fechadenacimiento3DateChanged
        calculate.setEnabled(true);
        //calculate.setOpaque(false);
    }//GEN-LAST:event_fechadenacimiento3DateChanged

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

    }//GEN-LAST:event_tableMouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed

        int selectedfiles = table.getSelectedRowCount();
        if (selectedfiles > 0) {
            String botones[] = {"  Sí   ", "   No   "};
            int eleccion = JOptionPane.showOptionDialog(this, "¿Desea eliminar la/s fila/s seleccionada/s?", "Título", 0, 0, null, botones, this);

            if (eleccion == JOptionPane.YES_OPTION) {
                //JOptionPane.showMessageDialog(null, "Las filas que se eliminarán son la fila: " + Arrays.toString(table.getSelectedRows()));
                //ArrayList<Integer> filasseleccionadas = new ArrayList<Integer>();
                int filasseleccionadas[] = new int[table.getSelectedRows().length];
                filasseleccionadas = table.getSelectedRows();

                //JOptionPane.showMessageDialog(null, "Cantidad de filas a eliminar: " + filasseleccionadas.length);
                for (int i = filasseleccionadas.length - 1; i >= 0; i--) {
                    //JOptionPane.showMessageDialog(null, "Fila " + filasseleccionadas[i]);
                    //JOptionPane.showMessageDialog(null, "fila a eliminar AHORA MISMO: " + filasseleccionadas[i]);
                    modelo.removeRow(filasseleccionadas[i]);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay fila/s seleccionada/s para eliminar"
                    + "\nPor favor seleccione!");
        }
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(N_Programa_Vacunacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(N_Programa_Vacunacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(N_Programa_Vacunacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(N_Programa_Vacunacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new N_Programa_Vacunacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton calculate;
    private org.freixas.jcalendar.JCalendarCombo fechaactual3;
    private org.freixas.jcalendar.JCalendarCombo fechadenacimiento3;
    private javax.swing.JComboBox<String> genero;
    private org.freixas.jcalendar.JCalendarCombo jCalendarCombo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
