/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Clases.O_Programa_Bibliot;
import java.text.SimpleDateFormat;
import java.util.Date;
import sun.util.calendar.BaseCalendar;

/**
 *
 * @author USUARIO
 */
public class O_Programa_Biblioteca extends javax.swing.JFrame {

    DefaultTableModel modelo;

    public O_Programa_Biblioteca() {
        initComponents();
        String datos[][] = {};
        String encabezado[] = {"Cedula", "Codigo", "Fecha Prestamo", "Prestamo", "Fecha Devolución", "Devolución", "Valor"};
        modelo = new DefaultTableModel(datos, encabezado);
        Registroprestamos.setModel(modelo);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Registroprestamos = new javax.swing.JTable();
        button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        opcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Chiller", 0, 51)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 9, 0));
        jLabel4.setText("Control - Prestamos de libros");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 460, -1));

        Registroprestamos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(182, 112, 46)));
        Registroprestamos.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        Registroprestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Registroprestamos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 841, 276));

        button.setBackground(new java.awt.Color(247, 233, 213));
        button.setFont(new java.awt.Font("Chiller", 0, 30)); // NOI18N
        button.setForeground(new java.awt.Color(38, 30, 18));
        button.setText("Aceptar");
        button.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(45, 28, 0), null));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        getContentPane().add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 110, 30));

        jLabel1.setFont(new java.awt.Font("Chiller", 0, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 16, 1));
        jLabel1.setText("Seleccione Tipo de servicio:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Chiller", 0, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 16, 1));
        jLabel2.setText("1)  Prestamo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Chiller", 0, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(41, 16, 1));
        jLabel3.setText("2)  Devolución");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Chiller", 0, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(41, 16, 1));
        jLabel5.setText("0)  Calcular Total recaudado");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, -1));

        opcion.setBackground(new java.awt.Color(0, 204, 204));
        opcion.setFont(new java.awt.Font("Chiller", 0, 25)); // NOI18N
        getContentPane().add(opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 63, 30));

        jLabel6.setFont(new java.awt.Font("Chiller", 0, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(41, 16, 1));
        jLabel6.setText("Opción:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondobiblioteca3.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setPreferredSize(new java.awt.Dimension(1250, 600));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed

        int opc = Integer.parseInt(opcion.getText());
        String oppc = opcion.getText();

        switch (opc) {
            case 1:
                int codigo = Integer.parseInt(JOptionPane.showInputDialog("Por favor, digite el codigo del libro que desea solicitar: "));
                if (O_Programa_Bibliot.Validar_Codigo(codigo)) {
                    if (O_Programa_Bibliot.Realizar_Prestamo(codigo)) {
                        int cedula = Integer.parseInt(JOptionPane.showInputDialog("Cedula: "));

                        Date fecha = new Date();
                        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYY");
                        String fechaa = formatofecha.format(fecha);

                        String Prestamo = "Realizado";
                        String Devolucion = "No Realizada";
                        String valor = "0";

                        String datostabla[] = {String.valueOf(cedula), String.valueOf(codigo), fechaa, Prestamo,
                            "", Devolucion, valor};
                        modelo.addRow(datostabla);

                    } else {
                        JOptionPane.showMessageDialog(null, "Lo sentimos,"
                                + "\nSolo se pueden prestar libros del área 101, 102 y 104,"
                                + "\nel libro que está solicitando no se encuentra en las áreas anteriormente mencionadas.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Lo sentimos, el codigo es inválido,"
                            + "\nNo se puede realizar el prestamo!"
                            + "\n\nRazones por las cuales el código es inválido:"
                            + "\n\n1) El codigo debe de ser un número de 8 dígitos. \n2) el área del libro debe estar entre 101 y 108."
                            + "\n3) La cantidad de libros existentes en Biblioteca debe ser diferente de de 1 en adelante."
                            + "\n\nUSTED CUMPLE CON ALGUNA DE LAS RAZONES ANTERIORES");
                }
                break;
            case 2:
                int cedula = Integer.parseInt(JOptionPane.showInputDialog("Cedula: "));

                Date fecha = new Date();
                SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYY");
                String fechaa = formatofecha.format(fecha);

                boolean cedulaencontrada = false;
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    if (cedula == Integer.parseInt((String) modelo.getValueAt(i, 0))) {
                        cedulaencontrada = true;
                        modelo.setValueAt(fechaa, i, 4);
                        modelo.setValueAt("Realizada", i, 5);
                        //String codigoo = (String) modelo.getValueAt(i, 1);
                        //double valor = O_Programa_Bibliot.Recibir_Libro_Prestado(Integer.parseInt((String) modelo.getValueAt(i, 1)));
                        //String valueOf = String.valueOf(O_Programa_Bibliot.Recibir_Libro_Prestado(Integer.parseInt((String) modelo.getValueAt(i, 1))));
                        modelo.setValueAt(String.valueOf(O_Programa_Bibliot.Recibir_Libro_Prestado(Integer.parseInt((String) modelo.getValueAt(i, 1)))), i, 6);
                        break;
                    }
                }

                if (cedulaencontrada == false) {
                    JOptionPane.showMessageDialog(null, "ALERTA!!!!"
                            + "\n\n¡USUARIO NO REGISTRADO!"
                            + "\nREGISTRAR ENSEGUIDA!!!!!!!!");
                }

                break;
            case 0:
                int cantidadrecaudada = 0;
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    cantidadrecaudada = cantidadrecaudada + Integer.parseInt(String.valueOf(modelo.getValueAt(i, 6)));
                }
                JOptionPane.showMessageDialog(null, "La cantidad de dinero recaudado hasta el momento es de: $ " + cantidadrecaudada);
                break;
            default:
                JOptionPane.showMessageDialog(null, "POR FAVOR, LEA BIEN!!! DIGITE UNA DE LAS OPCIONES ANTERIORES, 1, 2 o 0"
                        + "\nGRACIAS");
                break;
        }
    }//GEN-LAST:event_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(O_Programa_Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(O_Programa_Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(O_Programa_Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(O_Programa_Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new O_Programa_Biblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Registroprestamos;
    private javax.swing.JButton button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField opcion;
    // End of variables declaration//GEN-END:variables
}
