/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import Clases.J_Num_Narc;
import Clases.P_Ejercicio16;

/**
 *
 * @author USUARIO
 */
public class P_TablasMultiplicar_Unir_A_C_Invertirnum extends javax.swing.JFrame {

    /**
     * Creates new form A_Potencia_De_Un_Numero
     */
    public P_TablasMultiplicar_Unir_A_C_Invertirnum() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultado = new javax.swing.JTextArea();
        numero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button.setBackground(new java.awt.Color(255, 228, 190));
        button.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        button.setForeground(new java.awt.Color(38, 30, 18));
        button.setText("Calcular");
        button.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(45, 28, 0), null));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        getContentPane().add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 90, 30));

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(38, 30, 18));
        jLabel8.setText("Ejercicio 16");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        Resultado.setBackground(new java.awt.Color(255, 255, 255));
        Resultado.setColumns(20);
        Resultado.setRows(5);
        Resultado.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(72, 32, 3), null));
        jScrollPane1.setViewportView(Resultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 250, 240));
        getContentPane().add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 132, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(38, 30, 18));
        jLabel6.setText("Digita el número: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo16.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String tablasdemultiplicar = "";
    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed

        int num = Integer.parseInt(numero.getText());

        if (P_Ejercicio16.Verificarsiesde6digitos(num) == true) {

            int a = num / 10000;
            int b = (num / 100) % 100;
            int c = num % 100;

            if (a < b) {
                tablasdemultiplicar = P_Ejercicio16.Generar_Tablas_De_Mult(a, b);
                //JOptionPane.showMessageDialog(null, tablasdemultiplicar);
            } else {
                tablasdemultiplicar = "-----  NO APLICA  -----\n\n";
                JOptionPane.showMessageDialog(null, "No cumple con la condicion para generar las tablas de multiplicar!"
                        + "\nYa que a es mayor que b");
            }

            String numeroaycunido = a + "" + c;
            String numeroinvertido = "";

            while (num > 0) {
                int cifra = num % 10;
                numeroinvertido += cifra + "";
                num = num / 10;
            }

            Resultado.setText("TABLAS DE MULTIPLICAR" + "\n\n" + tablasdemultiplicar
                    + "NÚMERO A Y C UNIDO: " + numeroaycunido + "\n"
                    + "\nNÚMERO INVERTIDO: " + numeroinvertido + "\n\n");

        } else {
            JOptionPane.showMessageDialog(null, "Por favor, digite un numero de 6 digitos para"
                    + "\npoder realizar este ejercicio.");
        }


    }//GEN-LAST:event_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P_TablasMultiplicar_Unir_A_C_Invertirnum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P_TablasMultiplicar_Unir_A_C_Invertirnum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P_TablasMultiplicar_Unir_A_C_Invertirnum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P_TablasMultiplicar_Unir_A_C_Invertirnum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P_TablasMultiplicar_Unir_A_C_Invertirnum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Resultado;
    private javax.swing.JButton button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numero;
    // End of variables declaration//GEN-END:variables
}
